export enum FetchStudentsActions {
  FETCH_STUDENTS = "FETCH_STUDENTS",
  FETCH_STUDENTS_SUCCESSFUL = "FETCH_STUDENTS_SUCCESSFUL",
  FETCH_STUDENTS_FAILURE = "FETCH_STUDENTS_FAILURE",
}

export enum AddTagsToStudents {
  ADD_TAGS = "ADD_TAGS",
  ADD_TAGS_SUCCESSFUL = "ADD_TAGS_SUCCESSFUL",
  ADD_TAGS_FAILURE = "ADD_TAGS_FAILURE",
}
